# Generated by Django 4.2.7 on 2026-03-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="assignment_file",
            field=models.FileField(blank=True, null=True, upload_to="assignments/"),
        ),
        migrations.AddField(
            model_name="submission",
            name="submission_file",
            field=models.FileField(blank=True, null=True, upload_to="submissions/"),
        ),
    ]
